language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick libcairo2-dev
  - "2>/dev/null 1>/dev/null python -m SimpleHTTPServer 8001 &"

addons:
  sauce_connect: true

script: "npm test"

node_js:
  - node

notifications:
  email: false
