language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick libcairo2-dev

addons:
  sauce_connect: true

script: "npm test"

node_js:
  - node

notifications:
  email: false
